// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// BookWithTokenItemRequestBuilder builds and executes requests for operations under \clob\book\{tokenId}
type BookWithTokenItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// BookWithTokenItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type BookWithTokenItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewBookWithTokenItemRequestBuilderInternal instantiates a new BookWithTokenItemRequestBuilder and sets the default values.
func NewBookWithTokenItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*BookWithTokenItemRequestBuilder) {
    m := &BookWithTokenItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/clob/book/{tokenId}", pathParameters),
    }
    return m
}
// NewBookWithTokenItemRequestBuilder instantiates a new BookWithTokenItemRequestBuilder and sets the default values.
func NewBookWithTokenItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*BookWithTokenItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewBookWithTokenItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve the current order book for a specific token ID. Returns bids, asks, and market metadata including minimum order size and tick size. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// Deprecated: This method is obsolete. Use GetAsWithTokenGetResponse instead.
// returns a BookItemWithTokenResponseable when successful
// returns a BookItemWithToken400Error error when the service returns a 400 status code
// returns a BookItemWithToken404Error error when the service returns a 404 status code
// returns a BookItemWithToken500Error error when the service returns a 500 status code
func (m *BookWithTokenItemRequestBuilder) Get(ctx context.Context, requestConfiguration *BookWithTokenItemRequestBuilderGetRequestConfiguration)(BookItemWithTokenResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateBookItemWithToken400ErrorFromDiscriminatorValue,
        "404": CreateBookItemWithToken404ErrorFromDiscriminatorValue,
        "500": CreateBookItemWithToken500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateBookItemWithTokenResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(BookItemWithTokenResponseable), nil
}
// GetAsWithTokenGetResponse retrieve the current order book for a specific token ID. Returns bids, asks, and market metadata including minimum order size and tick size. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// returns a BookItemWithTokenGetResponseable when successful
// returns a BookItemWithToken400Error error when the service returns a 400 status code
// returns a BookItemWithToken404Error error when the service returns a 404 status code
// returns a BookItemWithToken500Error error when the service returns a 500 status code
func (m *BookWithTokenItemRequestBuilder) GetAsWithTokenGetResponse(ctx context.Context, requestConfiguration *BookWithTokenItemRequestBuilderGetRequestConfiguration)(BookItemWithTokenGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateBookItemWithToken400ErrorFromDiscriminatorValue,
        "404": CreateBookItemWithToken404ErrorFromDiscriminatorValue,
        "500": CreateBookItemWithToken500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateBookItemWithTokenGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(BookItemWithTokenGetResponseable), nil
}
// ToGetRequestInformation retrieve the current order book for a specific token ID. Returns bids, asks, and market metadata including minimum order size and tick size. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// returns a *RequestInformation when successful
func (m *BookWithTokenItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *BookWithTokenItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *BookWithTokenItemRequestBuilder when successful
func (m *BookWithTokenItemRequestBuilder) WithUrl(rawUrl string)(*BookWithTokenItemRequestBuilder) {
    return NewBookWithTokenItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
