// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CacheStatsGetResponse_sdkCache struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The maxSize property
    maxSize *float64
    // The size property
    size *float64
}
// NewCacheStatsGetResponse_sdkCache instantiates a new CacheStatsGetResponse_sdkCache and sets the default values.
func NewCacheStatsGetResponse_sdkCache()(*CacheStatsGetResponse_sdkCache) {
    m := &CacheStatsGetResponse_sdkCache{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCacheStatsGetResponse_sdkCacheFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCacheStatsGetResponse_sdkCacheFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCacheStatsGetResponse_sdkCache(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CacheStatsGetResponse_sdkCache) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CacheStatsGetResponse_sdkCache) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["maxSize"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMaxSize(val)
        }
        return nil
    }
    res["size"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSize(val)
        }
        return nil
    }
    return res
}
// GetMaxSize gets the maxSize property value. The maxSize property
// returns a *float64 when successful
func (m *CacheStatsGetResponse_sdkCache) GetMaxSize()(*float64) {
    return m.maxSize
}
// GetSize gets the size property value. The size property
// returns a *float64 when successful
func (m *CacheStatsGetResponse_sdkCache) GetSize()(*float64) {
    return m.size
}
// Serialize serializes information the current object
func (m *CacheStatsGetResponse_sdkCache) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("maxSize", m.GetMaxSize())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("size", m.GetSize())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CacheStatsGetResponse_sdkCache) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetMaxSize sets the maxSize property value. The maxSize property
func (m *CacheStatsGetResponse_sdkCache) SetMaxSize(value *float64)() {
    m.maxSize = value
}
// SetSize sets the size property value. The size property
func (m *CacheStatsGetResponse_sdkCache) SetSize(value *float64)() {
    m.size = value
}
type CacheStatsGetResponse_sdkCacheable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMaxSize()(*float64)
    GetSize()(*float64)
    SetMaxSize(value *float64)()
    SetSize(value *float64)()
}
