// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CacheDeleteResponseable instead.
type CacheResponse struct {
    CacheDeleteResponse
}
// NewCacheResponse instantiates a new CacheResponse and sets the default values.
func NewCacheResponse()(*CacheResponse) {
    m := &CacheResponse{
        CacheDeleteResponse: *NewCacheDeleteResponse(),
    }
    return m
}
// CreateCacheResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCacheResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCacheResponse(), nil
}
// Deprecated: This class is obsolete. Use CacheDeleteResponseable instead.
type CacheResponseable interface {
    CacheDeleteResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
