// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ClobRequestBuilder builds and executes requests for operations under \clob
type ClobRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Book the book property
// returns a *BookRequestBuilder when successful
func (m *ClobRequestBuilder) Book()(*BookRequestBuilder) {
    return NewBookRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Cache the cache property
// returns a *CacheRequestBuilder when successful
func (m *ClobRequestBuilder) Cache()(*CacheRequestBuilder) {
    return NewCacheRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewClobRequestBuilderInternal instantiates a new ClobRequestBuilder and sets the default values.
func NewClobRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ClobRequestBuilder) {
    m := &ClobRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/clob", pathParameters),
    }
    return m
}
// NewClobRequestBuilder instantiates a new ClobRequestBuilder and sets the default values.
func NewClobRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ClobRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewClobRequestBuilderInternal(urlParams, requestAdapter)
}
// Health the health property
// returns a *HealthRequestBuilder when successful
func (m *ClobRequestBuilder) Health()(*HealthRequestBuilder) {
    return NewHealthRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Market the market property
// returns a *MarketRequestBuilder when successful
func (m *ClobRequestBuilder) Market()(*MarketRequestBuilder) {
    return NewMarketRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Markets the markets property
// returns a *MarketsRequestBuilder when successful
func (m *ClobRequestBuilder) Markets()(*MarketsRequestBuilder) {
    return NewMarketsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Midpoint the midpoint property
// returns a *MidpointRequestBuilder when successful
func (m *ClobRequestBuilder) Midpoint()(*MidpointRequestBuilder) {
    return NewMidpointRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Midpoints the midpoints property
// returns a *MidpointsRequestBuilder when successful
func (m *ClobRequestBuilder) Midpoints()(*MidpointsRequestBuilder) {
    return NewMidpointsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Orderbooks the orderbooks property
// returns a *OrderbooksRequestBuilder when successful
func (m *ClobRequestBuilder) Orderbooks()(*OrderbooksRequestBuilder) {
    return NewOrderbooksRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Price the price property
// returns a *PriceRequestBuilder when successful
func (m *ClobRequestBuilder) Price()(*PriceRequestBuilder) {
    return NewPriceRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Prices the prices property
// returns a *PricesRequestBuilder when successful
func (m *ClobRequestBuilder) Prices()(*PricesRequestBuilder) {
    return NewPricesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// PricesHistory the pricesHistory property
// returns a *PricesHistoryRequestBuilder when successful
func (m *ClobRequestBuilder) PricesHistory()(*PricesHistoryRequestBuilder) {
    return NewPricesHistoryRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// SamplingMarkets the samplingMarkets property
// returns a *SamplingMarketsRequestBuilder when successful
func (m *ClobRequestBuilder) SamplingMarkets()(*SamplingMarketsRequestBuilder) {
    return NewSamplingMarketsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// SamplingSimplifiedMarkets the samplingSimplifiedMarkets property
// returns a *SamplingSimplifiedMarketsRequestBuilder when successful
func (m *ClobRequestBuilder) SamplingSimplifiedMarkets()(*SamplingSimplifiedMarketsRequestBuilder) {
    return NewSamplingSimplifiedMarketsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// SimplifiedMarkets the simplifiedMarkets property
// returns a *SimplifiedMarketsRequestBuilder when successful
func (m *ClobRequestBuilder) SimplifiedMarkets()(*SimplifiedMarketsRequestBuilder) {
    return NewSimplifiedMarketsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Spreads the spreads property
// returns a *SpreadsRequestBuilder when successful
func (m *ClobRequestBuilder) Spreads()(*SpreadsRequestBuilder) {
    return NewSpreadsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Trades the trades property
// returns a *TradesRequestBuilder when successful
func (m *ClobRequestBuilder) Trades()(*TradesRequestBuilder) {
    return NewTradesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
