// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MarketsRequestBuilder builds and executes requests for operations under \clob\markets
type MarketsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// MarketsRequestBuilderGetQueryParameters get paginated list of markets. Optional next_cursor for pagination. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
type MarketsRequestBuilderGetQueryParameters struct {
    Next_cursor *string `uriparametername:"next_cursor"`
}
// MarketsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type MarketsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *MarketsRequestBuilderGetQueryParameters
}
// NewMarketsRequestBuilderInternal instantiates a new MarketsRequestBuilder and sets the default values.
func NewMarketsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MarketsRequestBuilder) {
    m := &MarketsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/clob/markets{?next_cursor*}", pathParameters),
    }
    return m
}
// NewMarketsRequestBuilder instantiates a new MarketsRequestBuilder and sets the default values.
func NewMarketsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MarketsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMarketsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get paginated list of markets. Optional next_cursor for pagination. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// Deprecated: This method is obsolete. Use GetAsMarketsGetResponse instead.
// returns a MarketsResponseable when successful
// returns a Markets400Error error when the service returns a 400 status code
// returns a Markets500Error error when the service returns a 500 status code
func (m *MarketsRequestBuilder) Get(ctx context.Context, requestConfiguration *MarketsRequestBuilderGetRequestConfiguration)(MarketsResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateMarkets400ErrorFromDiscriminatorValue,
        "500": CreateMarkets500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateMarketsResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(MarketsResponseable), nil
}
// GetAsMarketsGetResponse get paginated list of markets. Optional next_cursor for pagination. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// returns a MarketsGetResponseable when successful
// returns a Markets400Error error when the service returns a 400 status code
// returns a Markets500Error error when the service returns a 500 status code
func (m *MarketsRequestBuilder) GetAsMarketsGetResponse(ctx context.Context, requestConfiguration *MarketsRequestBuilderGetRequestConfiguration)(MarketsGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateMarkets400ErrorFromDiscriminatorValue,
        "500": CreateMarkets500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateMarketsGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(MarketsGetResponseable), nil
}
// ToGetRequestInformation get paginated list of markets. Optional next_cursor for pagination. Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// returns a *RequestInformation when successful
func (m *MarketsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *MarketsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MarketsRequestBuilder when successful
func (m *MarketsRequestBuilder) WithUrl(rawUrl string)(*MarketsRequestBuilder) {
    return NewMarketsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
