// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MidpointItemWithTokenGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The midpoint property
    midpoint *float64
}
// NewMidpointItemWithTokenGetResponse instantiates a new MidpointItemWithTokenGetResponse and sets the default values.
func NewMidpointItemWithTokenGetResponse()(*MidpointItemWithTokenGetResponse) {
    m := &MidpointItemWithTokenGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMidpointItemWithTokenGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMidpointItemWithTokenGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMidpointItemWithTokenGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MidpointItemWithTokenGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MidpointItemWithTokenGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["midpoint"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMidpoint(val)
        }
        return nil
    }
    return res
}
// GetMidpoint gets the midpoint property value. The midpoint property
// returns a *float64 when successful
func (m *MidpointItemWithTokenGetResponse) GetMidpoint()(*float64) {
    return m.midpoint
}
// Serialize serializes information the current object
func (m *MidpointItemWithTokenGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("midpoint", m.GetMidpoint())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MidpointItemWithTokenGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetMidpoint sets the midpoint property value. The midpoint property
func (m *MidpointItemWithTokenGetResponse) SetMidpoint(value *float64)() {
    m.midpoint = value
}
type MidpointItemWithTokenGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMidpoint()(*float64)
    SetMidpoint(value *float64)()
}
