// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MidpointsPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The midpoints property
    midpoints []float64
}
// NewMidpointsPostResponse instantiates a new MidpointsPostResponse and sets the default values.
func NewMidpointsPostResponse()(*MidpointsPostResponse) {
    m := &MidpointsPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMidpointsPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMidpointsPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMidpointsPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MidpointsPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MidpointsPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["midpoints"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("float64")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]float64, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*float64))
                }
            }
            m.SetMidpoints(res)
        }
        return nil
    }
    return res
}
// GetMidpoints gets the midpoints property value. The midpoints property
// returns a []float64 when successful
func (m *MidpointsPostResponse) GetMidpoints()([]float64) {
    return m.midpoints
}
// Serialize serializes information the current object
func (m *MidpointsPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetMidpoints() != nil {
        err := writer.WriteCollectionOfFloat64Values("midpoints", m.GetMidpoints())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MidpointsPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetMidpoints sets the midpoints property value. The midpoints property
func (m *MidpointsPostResponse) SetMidpoints(value []float64)() {
    m.midpoints = value
}
type MidpointsPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMidpoints()([]float64)
    SetMidpoints(value []float64)()
}
