// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MidpointRequestBuilder builds and executes requests for operations under \clob\midpoint
type MidpointRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByTokenId gets an item from the go-polymarket/client.clob.midpoint.item collection
// returns a *MidpointWithTokenItemRequestBuilder when successful
func (m *MidpointRequestBuilder) ByTokenId(tokenId string)(*MidpointWithTokenItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if tokenId != "" {
        urlTplParams["tokenId"] = tokenId
    }
    return NewMidpointWithTokenItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewMidpointRequestBuilderInternal instantiates a new MidpointRequestBuilder and sets the default values.
func NewMidpointRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MidpointRequestBuilder) {
    m := &MidpointRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/clob/midpoint", pathParameters),
    }
    return m
}
// NewMidpointRequestBuilder instantiates a new MidpointRequestBuilder and sets the default values.
func NewMidpointRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MidpointRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMidpointRequestBuilderInternal(urlParams, requestAdapter)
}
