// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// OrderbooksRequestBuilder builds and executes requests for operations under \clob\orderbooks
type OrderbooksRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// OrderbooksRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type OrderbooksRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewOrderbooksRequestBuilderInternal instantiates a new OrderbooksRequestBuilder and sets the default values.
func NewOrderbooksRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OrderbooksRequestBuilder) {
    m := &OrderbooksRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/clob/orderbooks", pathParameters),
    }
    return m
}
// NewOrderbooksRequestBuilder instantiates a new OrderbooksRequestBuilder and sets the default values.
func NewOrderbooksRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OrderbooksRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewOrderbooksRequestBuilderInternal(urlParams, requestAdapter)
}
// Post retrieve order books for multiple token IDs. Each item should include token_id and optionally side (BUY/SELL). Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// returns a []Orderbooksable when successful
// returns a Orderbooks400Error error when the service returns a 400 status code
// returns a Orderbooks500Error error when the service returns a 500 status code
func (m *OrderbooksRequestBuilder) Post(ctx context.Context, body []Orderbooksable, requestConfiguration *OrderbooksRequestBuilderPostRequestConfiguration)([]Orderbooksable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateOrderbooks400ErrorFromDiscriminatorValue,
        "500": CreateOrderbooks500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateOrderbooksFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    val := make([]Orderbooksable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(Orderbooksable)
        }
    }
    return val, nil
}
// ToPostRequestInformation retrieve order books for multiple token IDs. Each item should include token_id and optionally side (BUY/SELL). Headers x-polymarket-key and x-polymarket-funder are required in production, optional in development (falls back to environment variables).
// returns a *RequestInformation when successful
func (m *OrderbooksRequestBuilder) ToPostRequestInformation(ctx context.Context, body []Orderbooksable, requestConfiguration *OrderbooksRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(body))
    for i, v := range body {
        if v != nil {
            cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
        }
    }
    err := requestInfo.SetContentFromParsableCollection(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", cast)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *OrderbooksRequestBuilder when successful
func (m *OrderbooksRequestBuilder) WithUrl(rawUrl string)(*OrderbooksRequestBuilder) {
    return NewOrderbooksRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
