// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PricesPostResponseable instead.
type PricesResponse struct {
    PricesPostResponse
}
// NewPricesResponse instantiates a new PricesResponse and sets the default values.
func NewPricesResponse()(*PricesResponse) {
    m := &PricesResponse{
        PricesPostResponse: *NewPricesPostResponse(),
    }
    return m
}
// CreatePricesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePricesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPricesResponse(), nil
}
// Deprecated: This class is obsolete. Use PricesPostResponseable instead.
type PricesResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PricesPostResponseable
}
