// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PricesHistoryGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The history property
    history []PricesHistoryGetResponse_historyable
    // The timeRange property
    timeRange PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable
}
// PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange composed type wrapper for classes PricesHistoryGetResponse_timeRangeMember1able, PricesHistoryGetResponse_timeRangeMember2able
type PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange struct {
    // Composed type representation for type PricesHistoryGetResponse_timeRangeMember1able
    pricesHistoryGetResponse_timeRangeMember1 PricesHistoryGetResponse_timeRangeMember1able
    // Composed type representation for type PricesHistoryGetResponse_timeRangeMember2able
    pricesHistoryGetResponse_timeRangeMember2 PricesHistoryGetResponse_timeRangeMember2able
}
// NewPricesHistoryGetResponse_PricesHistoryGetResponse_timeRange instantiates a new PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange and sets the default values.
func NewPricesHistoryGetResponse_PricesHistoryGetResponse_timeRange()(*PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) {
    m := &PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange{
    }
    return m
}
// CreatePricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPricesHistoryGetResponse_PricesHistoryGetResponse_timeRange()
    if parseNode != nil {
        if val, err := parseNode.GetObjectValue(CreatePricesHistoryGetResponse_timeRangeMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PricesHistoryGetResponse_timeRangeMember1able); ok {
                result.SetPricesHistoryGetResponseTimeRangeMember1(cast)
            }
        } else if val, err := parseNode.GetObjectValue(CreatePricesHistoryGetResponse_timeRangeMember2FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PricesHistoryGetResponse_timeRangeMember2able); ok {
                result.SetPricesHistoryGetResponseTimeRangeMember2(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) GetIsComposedType()(bool) {
    return true
}
// GetPricesHistoryGetResponseTimeRangeMember1 gets the PricesHistoryGetResponse_timeRangeMember1 property value. Composed type representation for type PricesHistoryGetResponse_timeRangeMember1able
// returns a PricesHistoryGetResponse_timeRangeMember1able when successful
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) GetPricesHistoryGetResponseTimeRangeMember1()(PricesHistoryGetResponse_timeRangeMember1able) {
    return m.pricesHistoryGetResponse_timeRangeMember1
}
// GetPricesHistoryGetResponseTimeRangeMember2 gets the PricesHistoryGetResponse_timeRangeMember2 property value. Composed type representation for type PricesHistoryGetResponse_timeRangeMember2able
// returns a PricesHistoryGetResponse_timeRangeMember2able when successful
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) GetPricesHistoryGetResponseTimeRangeMember2()(PricesHistoryGetResponse_timeRangeMember2able) {
    return m.pricesHistoryGetResponse_timeRangeMember2
}
// Serialize serializes information the current object
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetPricesHistoryGetResponseTimeRangeMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPricesHistoryGetResponseTimeRangeMember1())
        if err != nil {
            return err
        }
    } else if m.GetPricesHistoryGetResponseTimeRangeMember2() != nil {
        err := writer.WriteObjectValue("", m.GetPricesHistoryGetResponseTimeRangeMember2())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPricesHistoryGetResponseTimeRangeMember1 sets the PricesHistoryGetResponse_timeRangeMember1 property value. Composed type representation for type PricesHistoryGetResponse_timeRangeMember1able
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) SetPricesHistoryGetResponseTimeRangeMember1(value PricesHistoryGetResponse_timeRangeMember1able)() {
    m.pricesHistoryGetResponse_timeRangeMember1 = value
}
// SetPricesHistoryGetResponseTimeRangeMember2 sets the PricesHistoryGetResponse_timeRangeMember2 property value. Composed type representation for type PricesHistoryGetResponse_timeRangeMember2able
func (m *PricesHistoryGetResponse_PricesHistoryGetResponse_timeRange) SetPricesHistoryGetResponseTimeRangeMember2(value PricesHistoryGetResponse_timeRangeMember2able)() {
    m.pricesHistoryGetResponse_timeRangeMember2 = value
}
type PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPricesHistoryGetResponseTimeRangeMember1()(PricesHistoryGetResponse_timeRangeMember1able)
    GetPricesHistoryGetResponseTimeRangeMember2()(PricesHistoryGetResponse_timeRangeMember2able)
    SetPricesHistoryGetResponseTimeRangeMember1(value PricesHistoryGetResponse_timeRangeMember1able)()
    SetPricesHistoryGetResponseTimeRangeMember2(value PricesHistoryGetResponse_timeRangeMember2able)()
}
// NewPricesHistoryGetResponse instantiates a new PricesHistoryGetResponse and sets the default values.
func NewPricesHistoryGetResponse()(*PricesHistoryGetResponse) {
    m := &PricesHistoryGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePricesHistoryGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePricesHistoryGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPricesHistoryGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PricesHistoryGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PricesHistoryGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["history"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreatePricesHistoryGetResponse_historyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]PricesHistoryGetResponse_historyable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(PricesHistoryGetResponse_historyable)
                }
            }
            m.SetHistory(res)
        }
        return nil
    }
    res["timeRange"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTimeRange(val.(PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable))
        }
        return nil
    }
    return res
}
// GetHistory gets the history property value. The history property
// returns a []PricesHistoryGetResponse_historyable when successful
func (m *PricesHistoryGetResponse) GetHistory()([]PricesHistoryGetResponse_historyable) {
    return m.history
}
// GetTimeRange gets the timeRange property value. The timeRange property
// returns a PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable when successful
func (m *PricesHistoryGetResponse) GetTimeRange()(PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable) {
    return m.timeRange
}
// Serialize serializes information the current object
func (m *PricesHistoryGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetHistory() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetHistory()))
        for i, v := range m.GetHistory() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("history", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("timeRange", m.GetTimeRange())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PricesHistoryGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetHistory sets the history property value. The history property
func (m *PricesHistoryGetResponse) SetHistory(value []PricesHistoryGetResponse_historyable)() {
    m.history = value
}
// SetTimeRange sets the timeRange property value. The timeRange property
func (m *PricesHistoryGetResponse) SetTimeRange(value PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable)() {
    m.timeRange = value
}
type PricesHistoryGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetHistory()([]PricesHistoryGetResponse_historyable)
    GetTimeRange()(PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable)
    SetHistory(value []PricesHistoryGetResponse_historyable)()
    SetTimeRange(value PricesHistoryGetResponse_PricesHistoryGetResponse_timeRangeable)()
}
