// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package clob

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PriceRequestBuilder builds and executes requests for operations under \clob\price
type PriceRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByTokenId gets an item from the go-polymarket/client.clob.price.item collection
// returns a *PriceWithTokenItemRequestBuilder when successful
func (m *PriceRequestBuilder) ByTokenId(tokenId string)(*PriceWithTokenItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if tokenId != "" {
        urlTplParams["tokenId"] = tokenId
    }
    return NewPriceWithTokenItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewPriceRequestBuilderInternal instantiates a new PriceRequestBuilder and sets the default values.
func NewPriceRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PriceRequestBuilder) {
    m := &PriceRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/clob/price", pathParameters),
    }
    return m
}
// NewPriceRequestBuilder instantiates a new PriceRequestBuilder and sets the default values.
func NewPriceRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PriceRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPriceRequestBuilderInternal(urlParams, requestAdapter)
}
