package client

// API endpoint constants
const (
	CancelAll                    = "/cancel/all"
	CancelOrder                  = "/cancel/order"
	CreateApiKey                 = "/create/api-key"
	GetApiKeys                   = "/get/api-keys"
	ClosedOnly                   = "/get/closed-only-mode"
	GetOrder                     = "/get/order"
	PostOrder                    = "/post/order"
	Time                         = "/time"
	GetTrades                    = "/get/trades"
	GetOrderBook                 = "/get/orderbook"
	DeleteApiKey                 = "/delete/api-key"
	GetMidpoint                  = "/get/midpoint"
	GetPrice                     = "/get/price"
	GetOpenOrders                = "/get/orders"
	DeriveApiKey                 = "/derive/api-key"
	GetLastTradePrice            = "/get/last-trade-price"
	GetMarkets                   = "/get/markets"
	GetMarket                    = "/get/market/"
	GetPricesHistory             = "/get/price-history"
	GetNotifications             = "/get/notifications"
	DropNotifications            = "/drop/notifications"
	CancelOrders                 = "/cancel/orders"
	CancelMarketOrders           = "/cancel/market-orders"
	GetBalanceAllowance          = "/get/balance-allowance"
	IsOrderScoring               = "/is-order-scoring"
	GetTickSize                  = "/get/tick-size"
	GetNegRisk                   = "/get/neg-risk"
	AreOrdersScoring             = "/are-orders-scoring"
	GetSimplifiedMarkets         = "/get/simplified-markets"
	GetSamplingSimplifiedMarkets = "/get/sampling-simplified-markets"
	GetSamplingMarkets           = "/get/sampling-markets"
	GetMarketTradesEvents        = "/get/market-trades-events"
	GetOrderBooks                = "/get/orderbooks"
	GetMidpoints                 = "/get/midpoints"
	GetPrices                    = "/get/prices"
	GetLastTradesPrices          = "/get/last-trades-prices"
	GetEarningsForUserForDay     = "/get/earnings-for-user-for-day"
	GetLiquidityRewardPercentages= "/get/liquidity-reward-percentages"
	GetRewardsMarketsCurrent     = "/get/rewards-markets-current"
	GetRewardsMarkets            = "/get/rewards-markets/"
	GetRewardsEarningsPercentages= "/get/rewards-earnings-percentages"
	GetTotalEarningsForUserForDay= "/get/total-earnings-for-user-for-day"
	GetSpread                    = "/get/spread"
	GetSpreads                   = "/get/spreads"
	UpdateBalanceAllowance       = "/update/balance-allowance"
	PostOrders                   = "/post/orders"
	GetFeeRate                   = "/get/fee-rate"
	GetBuilderTrades             = "/get/builder-trades"
)