// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CommentsUser_addressItemWithUserAddress struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The body property
    body *string
    // The createdAt property
    createdAt *string
    // The id property
    id *string
    // The parentEntityID property
    parentEntityID *float64
    // The parentEntityType property
    parentEntityType *string
    // The profile property
    profile i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The reactionCount property
    reactionCount *float64
    // The reactions property
    reactions i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The reportCount property
    reportCount *float64
    // The userAddress property
    userAddress *string
}
// NewCommentsUser_addressItemWithUserAddress instantiates a new CommentsUser_addressItemWithUserAddress and sets the default values.
func NewCommentsUser_addressItemWithUserAddress()(*CommentsUser_addressItemWithUserAddress) {
    m := &CommentsUser_addressItemWithUserAddress{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCommentsUser_addressItemWithUserAddressFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCommentsUser_addressItemWithUserAddressFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCommentsUser_addressItemWithUserAddress(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CommentsUser_addressItemWithUserAddress) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBody gets the body property value. The body property
// returns a *string when successful
func (m *CommentsUser_addressItemWithUserAddress) GetBody()(*string) {
    return m.body
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *string when successful
func (m *CommentsUser_addressItemWithUserAddress) GetCreatedAt()(*string) {
    return m.createdAt
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CommentsUser_addressItemWithUserAddress) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["body"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBody(val)
        }
        return nil
    }
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["parentEntityID"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetParentEntityID(val)
        }
        return nil
    }
    res["parentEntityType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetParentEntityType(val)
        }
        return nil
    }
    res["profile"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfile(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["reactionCount"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReactionCount(val)
        }
        return nil
    }
    res["reactions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReactions(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["reportCount"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReportCount(val)
        }
        return nil
    }
    res["userAddress"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserAddress(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *CommentsUser_addressItemWithUserAddress) GetId()(*string) {
    return m.id
}
// GetParentEntityID gets the parentEntityID property value. The parentEntityID property
// returns a *float64 when successful
func (m *CommentsUser_addressItemWithUserAddress) GetParentEntityID()(*float64) {
    return m.parentEntityID
}
// GetParentEntityType gets the parentEntityType property value. The parentEntityType property
// returns a *string when successful
func (m *CommentsUser_addressItemWithUserAddress) GetParentEntityType()(*string) {
    return m.parentEntityType
}
// GetProfile gets the profile property value. The profile property
// returns a UntypedNodeable when successful
func (m *CommentsUser_addressItemWithUserAddress) GetProfile()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.profile
}
// GetReactionCount gets the reactionCount property value. The reactionCount property
// returns a *float64 when successful
func (m *CommentsUser_addressItemWithUserAddress) GetReactionCount()(*float64) {
    return m.reactionCount
}
// GetReactions gets the reactions property value. The reactions property
// returns a UntypedNodeable when successful
func (m *CommentsUser_addressItemWithUserAddress) GetReactions()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.reactions
}
// GetReportCount gets the reportCount property value. The reportCount property
// returns a *float64 when successful
func (m *CommentsUser_addressItemWithUserAddress) GetReportCount()(*float64) {
    return m.reportCount
}
// GetUserAddress gets the userAddress property value. The userAddress property
// returns a *string when successful
func (m *CommentsUser_addressItemWithUserAddress) GetUserAddress()(*string) {
    return m.userAddress
}
// Serialize serializes information the current object
func (m *CommentsUser_addressItemWithUserAddress) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("body", m.GetBody())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("parentEntityID", m.GetParentEntityID())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("parentEntityType", m.GetParentEntityType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("profile", m.GetProfile())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("reactionCount", m.GetReactionCount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("reactions", m.GetReactions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("reportCount", m.GetReportCount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userAddress", m.GetUserAddress())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CommentsUser_addressItemWithUserAddress) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBody sets the body property value. The body property
func (m *CommentsUser_addressItemWithUserAddress) SetBody(value *string)() {
    m.body = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *CommentsUser_addressItemWithUserAddress) SetCreatedAt(value *string)() {
    m.createdAt = value
}
// SetId sets the id property value. The id property
func (m *CommentsUser_addressItemWithUserAddress) SetId(value *string)() {
    m.id = value
}
// SetParentEntityID sets the parentEntityID property value. The parentEntityID property
func (m *CommentsUser_addressItemWithUserAddress) SetParentEntityID(value *float64)() {
    m.parentEntityID = value
}
// SetParentEntityType sets the parentEntityType property value. The parentEntityType property
func (m *CommentsUser_addressItemWithUserAddress) SetParentEntityType(value *string)() {
    m.parentEntityType = value
}
// SetProfile sets the profile property value. The profile property
func (m *CommentsUser_addressItemWithUserAddress) SetProfile(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.profile = value
}
// SetReactionCount sets the reactionCount property value. The reactionCount property
func (m *CommentsUser_addressItemWithUserAddress) SetReactionCount(value *float64)() {
    m.reactionCount = value
}
// SetReactions sets the reactions property value. The reactions property
func (m *CommentsUser_addressItemWithUserAddress) SetReactions(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.reactions = value
}
// SetReportCount sets the reportCount property value. The reportCount property
func (m *CommentsUser_addressItemWithUserAddress) SetReportCount(value *float64)() {
    m.reportCount = value
}
// SetUserAddress sets the userAddress property value. The userAddress property
func (m *CommentsUser_addressItemWithUserAddress) SetUserAddress(value *string)() {
    m.userAddress = value
}
type CommentsUser_addressItemWithUserAddressable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBody()(*string)
    GetCreatedAt()(*string)
    GetId()(*string)
    GetParentEntityID()(*float64)
    GetParentEntityType()(*string)
    GetProfile()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetReactionCount()(*float64)
    GetReactions()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetReportCount()(*float64)
    GetUserAddress()(*string)
    SetBody(value *string)()
    SetCreatedAt(value *string)()
    SetId(value *string)()
    SetParentEntityID(value *float64)()
    SetParentEntityType(value *string)()
    SetProfile(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetReactionCount(value *float64)()
    SetReactions(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetReportCount(value *float64)()
    SetUserAddress(value *string)()
}
