// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CommentsUser_addressWithUserAddressItemRequestBuilder builds and executes requests for operations under \gamma\comments\user_address\{userAddress}
type CommentsUser_addressWithUserAddressItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CommentsUser_addressWithUserAddressItemRequestBuilderGetQueryParameters retrieve comments made by a specific user address
type CommentsUser_addressWithUserAddressItemRequestBuilderGetQueryParameters struct {
    Ascending *bool `uriparametername:"ascending"`
    Limit *float64 `uriparametername:"limit"`
    Offset *float64 `uriparametername:"offset"`
    Order *string `uriparametername:"order"`
}
// CommentsUser_addressWithUserAddressItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CommentsUser_addressWithUserAddressItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *CommentsUser_addressWithUserAddressItemRequestBuilderGetQueryParameters
}
// NewCommentsUser_addressWithUserAddressItemRequestBuilderInternal instantiates a new CommentsUser_addressWithUserAddressItemRequestBuilder and sets the default values.
func NewCommentsUser_addressWithUserAddressItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CommentsUser_addressWithUserAddressItemRequestBuilder) {
    m := &CommentsUser_addressWithUserAddressItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/comments/user_address/{userAddress}{?ascending*,limit*,offset*,order*}", pathParameters),
    }
    return m
}
// NewCommentsUser_addressWithUserAddressItemRequestBuilder instantiates a new CommentsUser_addressWithUserAddressItemRequestBuilder and sets the default values.
func NewCommentsUser_addressWithUserAddressItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CommentsUser_addressWithUserAddressItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCommentsUser_addressWithUserAddressItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve comments made by a specific user address
// returns a []CommentsUser_addressItemWithUserAddressable when successful
// returns a CommentsUser_addressItemWithUserAddress500Error error when the service returns a 500 status code
func (m *CommentsUser_addressWithUserAddressItemRequestBuilder) Get(ctx context.Context, requestConfiguration *CommentsUser_addressWithUserAddressItemRequestBuilderGetRequestConfiguration)([]CommentsUser_addressItemWithUserAddressable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "500": CreateCommentsUser_addressItemWithUserAddress500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateCommentsUser_addressItemWithUserAddressFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    val := make([]CommentsUser_addressItemWithUserAddressable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(CommentsUser_addressItemWithUserAddressable)
        }
    }
    return val, nil
}
// ToGetRequestInformation retrieve comments made by a specific user address
// returns a *RequestInformation when successful
func (m *CommentsUser_addressWithUserAddressItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CommentsUser_addressWithUserAddressItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CommentsUser_addressWithUserAddressItemRequestBuilder when successful
func (m *CommentsUser_addressWithUserAddressItemRequestBuilder) WithUrl(rawUrl string)(*CommentsUser_addressWithUserAddressItemRequestBuilder) {
    return NewCommentsUser_addressWithUserAddressItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
