// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CommentsUser_addressRequestBuilder builds and executes requests for operations under \gamma\comments\user_address
type CommentsUser_addressRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByUserAddress gets an item from the go-polymarket/client.gamma.comments.user_address.item collection
// returns a *CommentsUser_addressWithUserAddressItemRequestBuilder when successful
func (m *CommentsUser_addressRequestBuilder) ByUserAddress(userAddress string)(*CommentsUser_addressWithUserAddressItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if userAddress != "" {
        urlTplParams["userAddress"] = userAddress
    }
    return NewCommentsUser_addressWithUserAddressItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewCommentsUser_addressRequestBuilderInternal instantiates a new CommentsUser_addressRequestBuilder and sets the default values.
func NewCommentsUser_addressRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CommentsUser_addressRequestBuilder) {
    m := &CommentsUser_addressRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/comments/user_address", pathParameters),
    }
    return m
}
// NewCommentsUser_addressRequestBuilder instantiates a new CommentsUser_addressRequestBuilder and sets the default values.
func NewCommentsUser_addressRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CommentsUser_addressRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCommentsUser_addressRequestBuilderInternal(urlParams, requestAdapter)
}
