// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// EventsRequestBuilder builds and executes requests for operations under \gamma\events
type EventsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// EventsRequestBuilderGetQueryParameters retrieve events with comprehensive filtering options
type EventsRequestBuilderGetQueryParameters struct {
    Active *bool `uriparametername:"active"`
    Archived *bool `uriparametername:"archived"`
    Ascending *bool `uriparametername:"ascending"`
    Closed *bool `uriparametername:"closed"`
    Cyom *bool `uriparametername:"cyom"`
    End_date_max *string `uriparametername:"end_date_max"`
    End_date_min *string `uriparametername:"end_date_min"`
    Exclude_tag_id []float64 `uriparametername:"exclude_tag_id"`
    Featured *bool `uriparametername:"featured"`
    Id []float64 `uriparametername:"id"`
    Include_chat *bool `uriparametername:"include_chat"`
    Include_template *bool `uriparametername:"include_template"`
    Limit *float64 `uriparametername:"limit"`
    Offset *float64 `uriparametername:"offset"`
    Order *string `uriparametername:"order"`
    Recurrence *string `uriparametername:"recurrence"`
    Slug []string `uriparametername:"slug"`
    Start_date_max *string `uriparametername:"start_date_max"`
    Start_date_min *string `uriparametername:"start_date_min"`
    Tag_id *float64 `uriparametername:"tag_id"`
}
// EventsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type EventsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *EventsRequestBuilderGetQueryParameters
}
// ById gets an item from the go-polymarket/client.gamma.events.item collection
// returns a *EventsEventsItemRequestBuilder when successful
func (m *EventsRequestBuilder) ById(id string)(*EventsEventsItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if id != "" {
        urlTplParams["id"] = id
    }
    return NewEventsEventsItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewEventsRequestBuilderInternal instantiates a new EventsRequestBuilder and sets the default values.
func NewEventsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EventsRequestBuilder) {
    m := &EventsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/events{?active*,archived*,ascending*,closed*,cyom*,end_date_max*,end_date_min*,exclude_tag_id*,featured*,id*,include_chat*,include_template*,limit*,offset*,order*,recurrence*,slug*,start_date_max*,start_date_min*,tag_id*}", pathParameters),
    }
    return m
}
// NewEventsRequestBuilder instantiates a new EventsRequestBuilder and sets the default values.
func NewEventsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EventsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewEventsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve events with comprehensive filtering options
// returns a []Eventsable when successful
// returns a Events500Error error when the service returns a 500 status code
func (m *EventsRequestBuilder) Get(ctx context.Context, requestConfiguration *EventsRequestBuilderGetRequestConfiguration)([]Eventsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "500": CreateEvents500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateEventsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    val := make([]Eventsable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(Eventsable)
        }
    }
    return val, nil
}
// Pagination the pagination property
// returns a *EventsPaginationRequestBuilder when successful
func (m *EventsRequestBuilder) Pagination()(*EventsPaginationRequestBuilder) {
    return NewEventsPaginationRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Slug the slug property
// returns a *EventsSlugRequestBuilder when successful
func (m *EventsRequestBuilder) Slug()(*EventsSlugRequestBuilder) {
    return NewEventsSlugRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToGetRequestInformation retrieve events with comprehensive filtering options
// returns a *RequestInformation when successful
func (m *EventsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *EventsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *EventsRequestBuilder when successful
func (m *EventsRequestBuilder) WithUrl(rawUrl string)(*EventsRequestBuilder) {
    return NewEventsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
