// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// EventsSlugRequestBuilder builds and executes requests for operations under \gamma\events\slug
type EventsSlugRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// BySlug gets an item from the go-polymarket/client.gamma.events.slug.item collection
// returns a *EventsSlugWithSlugItemRequestBuilder when successful
func (m *EventsSlugRequestBuilder) BySlug(slug string)(*EventsSlugWithSlugItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if slug != "" {
        urlTplParams["slug"] = slug
    }
    return NewEventsSlugWithSlugItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewEventsSlugRequestBuilderInternal instantiates a new EventsSlugRequestBuilder and sets the default values.
func NewEventsSlugRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EventsSlugRequestBuilder) {
    m := &EventsSlugRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/events/slug", pathParameters),
    }
    return m
}
// NewEventsSlugRequestBuilder instantiates a new EventsSlugRequestBuilder and sets the default values.
func NewEventsSlugRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EventsSlugRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewEventsSlugRequestBuilderInternal(urlParams, requestAdapter)
}
