// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type EventsSlugItemWithSlugGetResponse_tags struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The createdAt property
    createdAt *string
    // The forceShow property
    forceShow *bool
    // The id property
    id *string
    // The isCarousel property
    isCarousel *bool
    // The label property
    label *string
    // The slug property
    slug *string
}
// NewEventsSlugItemWithSlugGetResponse_tags instantiates a new EventsSlugItemWithSlugGetResponse_tags and sets the default values.
func NewEventsSlugItemWithSlugGetResponse_tags()(*EventsSlugItemWithSlugGetResponse_tags) {
    m := &EventsSlugItemWithSlugGetResponse_tags{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateEventsSlugItemWithSlugGetResponse_tagsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEventsSlugItemWithSlugGetResponse_tagsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEventsSlugItemWithSlugGetResponse_tags(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *string when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetCreatedAt()(*string) {
    return m.createdAt
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["forceShow"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetForceShow(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["isCarousel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsCarousel(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    res["slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSlug(val)
        }
        return nil
    }
    return res
}
// GetForceShow gets the forceShow property value. The forceShow property
// returns a *bool when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetForceShow()(*bool) {
    return m.forceShow
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetId()(*string) {
    return m.id
}
// GetIsCarousel gets the isCarousel property value. The isCarousel property
// returns a *bool when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetIsCarousel()(*bool) {
    return m.isCarousel
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetLabel()(*string) {
    return m.label
}
// GetSlug gets the slug property value. The slug property
// returns a *string when successful
func (m *EventsSlugItemWithSlugGetResponse_tags) GetSlug()(*string) {
    return m.slug
}
// Serialize serializes information the current object
func (m *EventsSlugItemWithSlugGetResponse_tags) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("forceShow", m.GetForceShow())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isCarousel", m.GetIsCarousel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("slug", m.GetSlug())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *EventsSlugItemWithSlugGetResponse_tags) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *EventsSlugItemWithSlugGetResponse_tags) SetCreatedAt(value *string)() {
    m.createdAt = value
}
// SetForceShow sets the forceShow property value. The forceShow property
func (m *EventsSlugItemWithSlugGetResponse_tags) SetForceShow(value *bool)() {
    m.forceShow = value
}
// SetId sets the id property value. The id property
func (m *EventsSlugItemWithSlugGetResponse_tags) SetId(value *string)() {
    m.id = value
}
// SetIsCarousel sets the isCarousel property value. The isCarousel property
func (m *EventsSlugItemWithSlugGetResponse_tags) SetIsCarousel(value *bool)() {
    m.isCarousel = value
}
// SetLabel sets the label property value. The label property
func (m *EventsSlugItemWithSlugGetResponse_tags) SetLabel(value *string)() {
    m.label = value
}
// SetSlug sets the slug property value. The slug property
func (m *EventsSlugItemWithSlugGetResponse_tags) SetSlug(value *string)() {
    m.slug = value
}
type EventsSlugItemWithSlugGetResponse_tagsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*string)
    GetForceShow()(*bool)
    GetId()(*string)
    GetIsCarousel()(*bool)
    GetLabel()(*string)
    GetSlug()(*string)
    SetCreatedAt(value *string)()
    SetForceShow(value *bool)()
    SetId(value *string)()
    SetIsCarousel(value *bool)()
    SetLabel(value *string)()
    SetSlug(value *string)()
}
