// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MarketsItemTags struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The createdAt property
    createdAt *string
    // The createdBy property
    createdBy *float64
    // The forceHide property
    forceHide *bool
    // The forceShow property
    forceShow *bool
    // The id property
    id *string
    // The isCarousel property
    isCarousel *bool
    // The label property
    label *string
    // The publishedAt property
    publishedAt *string
    // The slug property
    slug *string
    // The updatedAt property
    updatedAt *string
    // The updatedBy property
    updatedBy *float64
}
// NewMarketsItemTags instantiates a new MarketsItemTags and sets the default values.
func NewMarketsItemTags()(*MarketsItemTags) {
    m := &MarketsItemTags{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMarketsItemTagsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMarketsItemTagsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMarketsItemTags(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MarketsItemTags) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *string when successful
func (m *MarketsItemTags) GetCreatedAt()(*string) {
    return m.createdAt
}
// GetCreatedBy gets the createdBy property value. The createdBy property
// returns a *float64 when successful
func (m *MarketsItemTags) GetCreatedBy()(*float64) {
    return m.createdBy
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MarketsItemTags) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["createdBy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedBy(val)
        }
        return nil
    }
    res["forceHide"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetForceHide(val)
        }
        return nil
    }
    res["forceShow"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetForceShow(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["isCarousel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsCarousel(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    res["publishedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPublishedAt(val)
        }
        return nil
    }
    res["slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSlug(val)
        }
        return nil
    }
    res["updatedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["updatedBy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedBy(val)
        }
        return nil
    }
    return res
}
// GetForceHide gets the forceHide property value. The forceHide property
// returns a *bool when successful
func (m *MarketsItemTags) GetForceHide()(*bool) {
    return m.forceHide
}
// GetForceShow gets the forceShow property value. The forceShow property
// returns a *bool when successful
func (m *MarketsItemTags) GetForceShow()(*bool) {
    return m.forceShow
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *MarketsItemTags) GetId()(*string) {
    return m.id
}
// GetIsCarousel gets the isCarousel property value. The isCarousel property
// returns a *bool when successful
func (m *MarketsItemTags) GetIsCarousel()(*bool) {
    return m.isCarousel
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *MarketsItemTags) GetLabel()(*string) {
    return m.label
}
// GetPublishedAt gets the publishedAt property value. The publishedAt property
// returns a *string when successful
func (m *MarketsItemTags) GetPublishedAt()(*string) {
    return m.publishedAt
}
// GetSlug gets the slug property value. The slug property
// returns a *string when successful
func (m *MarketsItemTags) GetSlug()(*string) {
    return m.slug
}
// GetUpdatedAt gets the updatedAt property value. The updatedAt property
// returns a *string when successful
func (m *MarketsItemTags) GetUpdatedAt()(*string) {
    return m.updatedAt
}
// GetUpdatedBy gets the updatedBy property value. The updatedBy property
// returns a *float64 when successful
func (m *MarketsItemTags) GetUpdatedBy()(*float64) {
    return m.updatedBy
}
// Serialize serializes information the current object
func (m *MarketsItemTags) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("createdBy", m.GetCreatedBy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("forceHide", m.GetForceHide())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("forceShow", m.GetForceShow())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isCarousel", m.GetIsCarousel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("publishedAt", m.GetPublishedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("slug", m.GetSlug())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("updatedAt", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("updatedBy", m.GetUpdatedBy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MarketsItemTags) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *MarketsItemTags) SetCreatedAt(value *string)() {
    m.createdAt = value
}
// SetCreatedBy sets the createdBy property value. The createdBy property
func (m *MarketsItemTags) SetCreatedBy(value *float64)() {
    m.createdBy = value
}
// SetForceHide sets the forceHide property value. The forceHide property
func (m *MarketsItemTags) SetForceHide(value *bool)() {
    m.forceHide = value
}
// SetForceShow sets the forceShow property value. The forceShow property
func (m *MarketsItemTags) SetForceShow(value *bool)() {
    m.forceShow = value
}
// SetId sets the id property value. The id property
func (m *MarketsItemTags) SetId(value *string)() {
    m.id = value
}
// SetIsCarousel sets the isCarousel property value. The isCarousel property
func (m *MarketsItemTags) SetIsCarousel(value *bool)() {
    m.isCarousel = value
}
// SetLabel sets the label property value. The label property
func (m *MarketsItemTags) SetLabel(value *string)() {
    m.label = value
}
// SetPublishedAt sets the publishedAt property value. The publishedAt property
func (m *MarketsItemTags) SetPublishedAt(value *string)() {
    m.publishedAt = value
}
// SetSlug sets the slug property value. The slug property
func (m *MarketsItemTags) SetSlug(value *string)() {
    m.slug = value
}
// SetUpdatedAt sets the updatedAt property value. The updatedAt property
func (m *MarketsItemTags) SetUpdatedAt(value *string)() {
    m.updatedAt = value
}
// SetUpdatedBy sets the updatedBy property value. The updatedBy property
func (m *MarketsItemTags) SetUpdatedBy(value *float64)() {
    m.updatedBy = value
}
type MarketsItemTagsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*string)
    GetCreatedBy()(*float64)
    GetForceHide()(*bool)
    GetForceShow()(*bool)
    GetId()(*string)
    GetIsCarousel()(*bool)
    GetLabel()(*string)
    GetPublishedAt()(*string)
    GetSlug()(*string)
    GetUpdatedAt()(*string)
    GetUpdatedBy()(*float64)
    SetCreatedAt(value *string)()
    SetCreatedBy(value *float64)()
    SetForceHide(value *bool)()
    SetForceShow(value *bool)()
    SetId(value *string)()
    SetIsCarousel(value *bool)()
    SetLabel(value *string)()
    SetPublishedAt(value *string)()
    SetSlug(value *string)()
    SetUpdatedAt(value *string)()
    SetUpdatedBy(value *float64)()
}
