// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MarketsItemTagsRequestBuilder builds and executes requests for operations under \gamma\markets\{id}\tags
type MarketsItemTagsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// MarketsItemTagsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type MarketsItemTagsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewMarketsItemTagsRequestBuilderInternal instantiates a new MarketsItemTagsRequestBuilder and sets the default values.
func NewMarketsItemTagsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MarketsItemTagsRequestBuilder) {
    m := &MarketsItemTagsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/markets/{id}/tags", pathParameters),
    }
    return m
}
// NewMarketsItemTagsRequestBuilder instantiates a new MarketsItemTagsRequestBuilder and sets the default values.
func NewMarketsItemTagsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MarketsItemTagsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMarketsItemTagsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve tags associated with a specific market
// returns a []MarketsItemTagsable when successful
// returns a MarketsItemTags404Error error when the service returns a 404 status code
// returns a MarketsItemTags500Error error when the service returns a 500 status code
func (m *MarketsItemTagsRequestBuilder) Get(ctx context.Context, requestConfiguration *MarketsItemTagsRequestBuilderGetRequestConfiguration)([]MarketsItemTagsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "404": CreateMarketsItemTags404ErrorFromDiscriminatorValue,
        "500": CreateMarketsItemTags500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateMarketsItemTagsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    val := make([]MarketsItemTagsable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(MarketsItemTagsable)
        }
    }
    return val, nil
}
// ToGetRequestInformation retrieve tags associated with a specific market
// returns a *RequestInformation when successful
func (m *MarketsItemTagsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *MarketsItemTagsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MarketsItemTagsRequestBuilder when successful
func (m *MarketsItemTagsRequestBuilder) WithUrl(rawUrl string)(*MarketsItemTagsRequestBuilder) {
    return NewMarketsItemTagsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
