// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MarketsSlugRequestBuilder builds and executes requests for operations under \gamma\markets\slug
type MarketsSlugRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// BySlug gets an item from the go-polymarket/client.gamma.markets.slug.item collection
// returns a *MarketsSlugWithSlugItemRequestBuilder when successful
func (m *MarketsSlugRequestBuilder) BySlug(slug string)(*MarketsSlugWithSlugItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if slug != "" {
        urlTplParams["slug"] = slug
    }
    return NewMarketsSlugWithSlugItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewMarketsSlugRequestBuilderInternal instantiates a new MarketsSlugRequestBuilder and sets the default values.
func NewMarketsSlugRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MarketsSlugRequestBuilder) {
    m := &MarketsSlugRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/markets/slug", pathParameters),
    }
    return m
}
// NewMarketsSlugRequestBuilder instantiates a new MarketsSlugRequestBuilder and sets the default values.
func NewMarketsSlugRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MarketsSlugRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMarketsSlugRequestBuilderInternal(urlParams, requestAdapter)
}
