// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MarketsSlugItemWithSlugGetResponseable instead.
type MarketsSlugItemWithSlugResponse struct {
    MarketsSlugItemWithSlugGetResponse
}
// NewMarketsSlugItemWithSlugResponse instantiates a new MarketsSlugItemWithSlugResponse and sets the default values.
func NewMarketsSlugItemWithSlugResponse()(*MarketsSlugItemWithSlugResponse) {
    m := &MarketsSlugItemWithSlugResponse{
        MarketsSlugItemWithSlugGetResponse: *NewMarketsSlugItemWithSlugGetResponse(),
    }
    return m
}
// CreateMarketsSlugItemWithSlugResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMarketsSlugItemWithSlugResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMarketsSlugItemWithSlugResponse(), nil
}
// Deprecated: This class is obsolete. Use MarketsSlugItemWithSlugGetResponseable instead.
type MarketsSlugItemWithSlugResponseable interface {
    MarketsSlugItemWithSlugGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
