// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// TagsSlugItemRelatedTagsTagsRequestBuilder builds and executes requests for operations under \gamma\tags\slug\{slug}\related-tags\tags
type TagsSlugItemRelatedTagsTagsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// TagsSlugItemRelatedTagsTagsRequestBuilderGetQueryParameters retrieve actual tag objects related to a specific tag slug
type TagsSlugItemRelatedTagsTagsRequestBuilderGetQueryParameters struct {
    Omit_empty *bool `uriparametername:"omit_empty"`
    Status *string `uriparametername:"status"`
}
// TagsSlugItemRelatedTagsTagsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TagsSlugItemRelatedTagsTagsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *TagsSlugItemRelatedTagsTagsRequestBuilderGetQueryParameters
}
// NewTagsSlugItemRelatedTagsTagsRequestBuilderInternal instantiates a new TagsSlugItemRelatedTagsTagsRequestBuilder and sets the default values.
func NewTagsSlugItemRelatedTagsTagsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TagsSlugItemRelatedTagsTagsRequestBuilder) {
    m := &TagsSlugItemRelatedTagsTagsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/tags/slug/{slug}/related-tags/tags{?omit_empty*,status*}", pathParameters),
    }
    return m
}
// NewTagsSlugItemRelatedTagsTagsRequestBuilder instantiates a new TagsSlugItemRelatedTagsTagsRequestBuilder and sets the default values.
func NewTagsSlugItemRelatedTagsTagsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TagsSlugItemRelatedTagsTagsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewTagsSlugItemRelatedTagsTagsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve actual tag objects related to a specific tag slug
// returns a []TagsSlugItemRelatedTagsTagsable when successful
// returns a TagsSlugItemRelatedTagsTags500Error error when the service returns a 500 status code
func (m *TagsSlugItemRelatedTagsTagsRequestBuilder) Get(ctx context.Context, requestConfiguration *TagsSlugItemRelatedTagsTagsRequestBuilderGetRequestConfiguration)([]TagsSlugItemRelatedTagsTagsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "500": CreateTagsSlugItemRelatedTagsTags500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateTagsSlugItemRelatedTagsTagsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    val := make([]TagsSlugItemRelatedTagsTagsable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(TagsSlugItemRelatedTagsTagsable)
        }
    }
    return val, nil
}
// ToGetRequestInformation retrieve actual tag objects related to a specific tag slug
// returns a *RequestInformation when successful
func (m *TagsSlugItemRelatedTagsTagsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *TagsSlugItemRelatedTagsTagsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TagsSlugItemRelatedTagsTagsRequestBuilder when successful
func (m *TagsSlugItemRelatedTagsTagsRequestBuilder) WithUrl(rawUrl string)(*TagsSlugItemRelatedTagsTagsRequestBuilder) {
    return NewTagsSlugItemRelatedTagsTagsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
