// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TagsItemRelatedTags struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The id property
    id *string
    // The rank property
    rank *float64
    // The relatedTagID property
    relatedTagID *float64
    // The tagID property
    tagID *float64
}
// NewTagsItemRelatedTags instantiates a new TagsItemRelatedTags and sets the default values.
func NewTagsItemRelatedTags()(*TagsItemRelatedTags) {
    m := &TagsItemRelatedTags{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateTagsItemRelatedTagsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTagsItemRelatedTagsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTagsItemRelatedTags(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *TagsItemRelatedTags) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TagsItemRelatedTags) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["rank"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRank(val)
        }
        return nil
    }
    res["relatedTagID"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRelatedTagID(val)
        }
        return nil
    }
    res["tagID"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTagID(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *TagsItemRelatedTags) GetId()(*string) {
    return m.id
}
// GetRank gets the rank property value. The rank property
// returns a *float64 when successful
func (m *TagsItemRelatedTags) GetRank()(*float64) {
    return m.rank
}
// GetRelatedTagID gets the relatedTagID property value. The relatedTagID property
// returns a *float64 when successful
func (m *TagsItemRelatedTags) GetRelatedTagID()(*float64) {
    return m.relatedTagID
}
// GetTagID gets the tagID property value. The tagID property
// returns a *float64 when successful
func (m *TagsItemRelatedTags) GetTagID()(*float64) {
    return m.tagID
}
// Serialize serializes information the current object
func (m *TagsItemRelatedTags) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("rank", m.GetRank())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("relatedTagID", m.GetRelatedTagID())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("tagID", m.GetTagID())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *TagsItemRelatedTags) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetId sets the id property value. The id property
func (m *TagsItemRelatedTags) SetId(value *string)() {
    m.id = value
}
// SetRank sets the rank property value. The rank property
func (m *TagsItemRelatedTags) SetRank(value *float64)() {
    m.rank = value
}
// SetRelatedTagID sets the relatedTagID property value. The relatedTagID property
func (m *TagsItemRelatedTags) SetRelatedTagID(value *float64)() {
    m.relatedTagID = value
}
// SetTagID sets the tagID property value. The tagID property
func (m *TagsItemRelatedTags) SetTagID(value *float64)() {
    m.tagID = value
}
type TagsItemRelatedTagsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetId()(*string)
    GetRank()(*float64)
    GetRelatedTagID()(*float64)
    GetTagID()(*float64)
    SetId(value *string)()
    SetRank(value *float64)()
    SetRelatedTagID(value *float64)()
    SetTagID(value *float64)()
}
