// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package gamma

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// TagsItemRelatedTagsRequestBuilder builds and executes requests for operations under \gamma\tags\{id}\related-tags
type TagsItemRelatedTagsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// TagsItemRelatedTagsRequestBuilderGetQueryParameters retrieve related tag relationships for a specific tag ID
type TagsItemRelatedTagsRequestBuilderGetQueryParameters struct {
    Omit_empty *bool `uriparametername:"omit_empty"`
    Status *string `uriparametername:"status"`
}
// TagsItemRelatedTagsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TagsItemRelatedTagsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *TagsItemRelatedTagsRequestBuilderGetQueryParameters
}
// NewTagsItemRelatedTagsRequestBuilderInternal instantiates a new TagsItemRelatedTagsRequestBuilder and sets the default values.
func NewTagsItemRelatedTagsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TagsItemRelatedTagsRequestBuilder) {
    m := &TagsItemRelatedTagsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/gamma/tags/{id}/related-tags{?omit_empty*,status*}", pathParameters),
    }
    return m
}
// NewTagsItemRelatedTagsRequestBuilder instantiates a new TagsItemRelatedTagsRequestBuilder and sets the default values.
func NewTagsItemRelatedTagsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*TagsItemRelatedTagsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewTagsItemRelatedTagsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve related tag relationships for a specific tag ID
// returns a []TagsItemRelatedTagsable when successful
// returns a TagsItemRelatedTags500Error error when the service returns a 500 status code
func (m *TagsItemRelatedTagsRequestBuilder) Get(ctx context.Context, requestConfiguration *TagsItemRelatedTagsRequestBuilderGetRequestConfiguration)([]TagsItemRelatedTagsable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "500": CreateTagsItemRelatedTags500ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateTagsItemRelatedTagsFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    val := make([]TagsItemRelatedTagsable, len(res))
    for i, v := range res {
        if v != nil {
            val[i] = v.(TagsItemRelatedTagsable)
        }
    }
    return val, nil
}
// Tags the tags property
// returns a *TagsItemRelatedTagsTagsRequestBuilder when successful
func (m *TagsItemRelatedTagsRequestBuilder) Tags()(*TagsItemRelatedTagsTagsRequestBuilder) {
    return NewTagsItemRelatedTagsTagsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToGetRequestInformation retrieve related tag relationships for a specific tag ID
// returns a *RequestInformation when successful
func (m *TagsItemRelatedTagsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *TagsItemRelatedTagsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TagsItemRelatedTagsRequestBuilder when successful
func (m *TagsItemRelatedTagsRequestBuilder) WithUrl(rawUrl string)(*TagsItemRelatedTagsRequestBuilder) {
    return NewTagsItemRelatedTagsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
