// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package priceshistory
type GetIntervalQueryParameterType int

const (
    ONEM_GETINTERVALQUERYPARAMETERTYPE GetIntervalQueryParameterType = iota
    ONEH_GETINTERVALQUERYPARAMETERTYPE
    SIXH_GETINTERVALQUERYPARAMETERTYPE
    ONED_GETINTERVALQUERYPARAMETERTYPE
    ONEW_GETINTERVALQUERYPARAMETERTYPE
    MAX_GETINTERVALQUERYPARAMETERTYPE
)

func (i GetIntervalQueryParameterType) String() string {
    return []string{"1m", "1h", "6h", "1d", "1w", "max"}[i]
}
func ParseGetIntervalQueryParameterType(v string) (any, error) {
    result := ONEM_GETINTERVALQUERYPARAMETERTYPE
    switch v {
        case "1m":
            result = ONEM_GETINTERVALQUERYPARAMETERTYPE
        case "1h":
            result = ONEH_GETINTERVALQUERYPARAMETERTYPE
        case "6h":
            result = SIXH_GETINTERVALQUERYPARAMETERTYPE
        case "1d":
            result = ONED_GETINTERVALQUERYPARAMETERTYPE
        case "1w":
            result = ONEW_GETINTERVALQUERYPARAMETERTYPE
        case "max":
            result = MAX_GETINTERVALQUERYPARAMETERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGetIntervalQueryParameterType(values []GetIntervalQueryParameterType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GetIntervalQueryParameterType) isMultiValue() bool {
    return false
}
